services:
  postgres:
    image: postgres:15-alpine
    container_name: wizard_postgres
    environment:
      POSTGRES_USER: wizard_user
      POSTGRES_PASSWORD: wizard_pass
      POSTGRES_DB: wizard_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
